DROP TABLE Butacas CASCADE CONSTRAINTS;
DROP TABLE Sesiones CASCADE CONSTRAINTS;
DROP TABLE Peliculas CASCADE CONSTRAINTS;
DROP TABLE Clientes CASCADE CONSTRAINTS;
DROP TABLE Cliente_Control CASCADE CONSTRAINTS;
DROP TABLE Reservas CASCADE CONSTRAINTS;
DROP TABLE Menus CASCADE CONSTRAINTS;
DROP TABLE ButacasReservas CASCADE CONSTRAINTS;
COMMIT;